// EXCEPTION / ERROR HANDLING 

// let b =12;
// let sum = a+b ;
// console.log(sum);
// console.log("Hello world");

// note: 1. This code runs when there is error in the code and it helps to not to stop the code or program -- it just give the error message and continue the program.

// try{
//     let b =12;
//     let sum = a+b ;
//     console.log(sum);
// }catch (error){
//     console.log(error.name, "something went wrong");   //----> always write (error (it gives the name of error), message);
// }finally{
//     console.log("This code will run anyway") //---> This code will run even even if TRY and CATCH do not run.
// }
// console.log("hello world");

// --------------------------------------------------------------------------------------------

// WHEN WE CREATE THE ERROR MANUALLY

// try{
//     let a = 13;
//     let b =12;
//     let sum = a+b ;
//     console.log(sum);

//     if(sum % 2!= 0){
//         throw Error("Odd values not allowed");
//     }
// }catch (error){
//     console.log(error.name, ":", "something went wrong");   //----> always write (error (it gives the name of error), message);
// }finally{
//     console.log("This code will run anyway") //---> This code will run even even if TRY and CATCH do not run.
// }
// console.log("hello world");

// --------------------------------------------------------------------------------------------

